### ISSUE TITLE
Wrong data for BCHexEditorEx1.SelectionAsHex

### ISSUE THREAD

**Issue by piker00** [bonecode/BCHexEditor#1]
Subject.

**Comment by NilsHoyer** [comment]
`SelectionAsHex` is a property - not a method. So I can't give a 
parmeter. But I can test this:

     BCHexEditor1.SelectionAsHex := #1;

... but it works fine on my end - without error message.

Can you assist me to understand the problem?

**Comment by piker00** [comment]
Here is video about:
![1](https://cloud.githubusercontent.com/assets/11677236/25615227/b8fc74b6-2f3e-11e7-959b-9a8ccf85aa65.gif)

soure 35 34 6A 74 69 76 34 35 75 69 74 6D 39 35
result 35 6A 69 34 75 74 39 34 75 68 63 69 72 76

code is:

`  Clipboard.SetTextBuf( PWideChar( BCHexEditorEx2.SelectionAsHex) );`

**Comment by NilsHoyer** [comment]
Thank you for your video and description. I've fixed this bug and commited it.
