### ISSUE TITLE
No 64-bit support?

### ISSUE THREAD

**Issue by PeterPanino** [bonecode/BCHexEditor#3]
When trying to compile the package for 64 bit I got this error message:

[dcc64 Error] BCHexEditor.pas(2023): E1025 Unsupported language feature: 'ASM'

So does BCHexEditor not work in 64-bit programs?

**Comment by PeterPanino** [comment]
Embarcadero states: DCC64.EXE supports 64-bit assembly code, with some limitations. Routines must be written completely in Delphi or in assembler (no mixing is allowed).

http://docwiki.embarcadero.com/RADStudio/XE2/en/DCC64.EXE,_the_Delphi_64-bit_Command_Line_Compiler#64-bit_Inline_Assembler

**Comment by NilsHoyer** [comment]
... implemented for you. Now, there is no ASM code further more.
