### ISSUE TITLE
Bug in PUndoRec function

### ISSUE THREAD

**Issue by BasePointer** [bonecode/BCHexEditor#5]
```
  function PUndoRec: PBCHUndoRec;
  begin
    Result := PBCHUndoRec(@(PChar(Memory)[urPos]))
  end;
```

Well here, programmer meant to say Result := PBCHUndoRec(@(**PByte**(Memory)[urPos]))

Raw PChar pointer will increment by 2 with delphi XE10.

**Comment by NilsHoyer** [comment]
I've fixed this issue. Thank you.
